### ISSUE TITLE
need a logo?

### ISSUE THREAD

**Issue by meldra** [LithApp/Lith#117]
Do you have a logo or branding yet? the app currently seems to be using a default logo on android.

I could do one up if I knew what you were after; "lith" is a bit ambiguous in terms of what you might have been intending with the name.

**Comment by MartinBriza** [comment]
There already sort-of is something: https://github.com/LithApp/Lith/blob/master/assets/icons/appstore.png , but this is something i stitched up in Inkscape in like 3 minutes so if you can come up with something more pleasing, it'll be more than welcome! 

I was thinking something like a menhir, monolith, that sort of thing. 

This picture being missing on Android is however just a matter of me never really setting up the metadata in the Android build right, so it's a buildsystem issue on top of my crappy design skills

**Comment by meldra** [comment]
How's this?

![lithapp](https://user-images.githubusercontent.com/1224145/178123250-eac42f6c-f2cb-4948-a4e5-334aae1a38e9.png)

I could do stacked stones as the "ellipsis" if you prefer. I think I prefer the ivy though as it breaks the color monotony.

**Comment by MartinBriza** [comment]
That's actually great, thanks! I really lake the shape of the stone in the middle. 
I have a few nitpicks that would make it more in line with my ideas though (and sorry for making so many demands, I really appreciate the work you've done):
 - The circle mask around it shouldn't exist, some platforms have square icons and we need to use the same icon everywhere, just cropping it to whatever shape is expected on iOS/Android/Windows... etc
 - I'd probably prefer the "ground" part to be flat
 - I think the colors should be a little more contrasting - I think shifting the sky color to a darker blue and the stone to a darker more gray color would work well.

As for the ivy, maybe we could add a birch tree instead? We could also experiment with making the leaves orange/brownish for an autumn-like aesthetic. The tree doesn't have to absolutely look like an actual birch tree, it's just that my surname means "birch" and, uhh, yeah, this is a little egoistic lol.

**Comment by meldra** [comment]
![lithappdarker](https://user-images.githubusercontent.com/1224145/179371740-dbe38169-9229-4cf7-87b8-f1133cd95c86.png)

**Comment by meldra** [comment]
i'll fix the color on that crack in a bit (inkscape crashed lol), but this is where i'm at

**Comment by meldra** [comment]
![lithappdarker](https://user-images.githubusercontent.com/1224145/179371848-861efe19-b52d-477b-98e6-484882f1a7b6.png)

**Comment by meldra** [comment]
![lithappdarker](https://user-images.githubusercontent.com/1224145/179717013-7e4f23d1-fca0-49d1-b8ef-86dc2a385b20.png)

**Comment by MartinBriza** [comment]
Hi, I'm very sorry about leaving this open for so long after you've invested your time into creating these designs. Your icons are great and they're all without a doubt way better than the abomination I created. However, and I know this is really not nice from me especially after all this time, it's unfortunately not what I had in on my mind. I'll just stick to the current logo for now and see about the options at some point.

Again, sorry. I'll try to make this up to you at least a little bit by making the Android builds work again.
