### ISSUE TITLE
Bufferlist counts only to 10

### ISSUE THREAD

**Issue by misterhsp** [LithApp/Lith#120]
In the bufferlist the numbering goes only from 1 to 10, although 28 channels are available. Is this a bug or is it intentional?

...

**Comment by MartinBriza** [comment]
This is intentional because you can switch between those buffers with alt+<number> but I understand why it's confusing to you... especially because that's not possible on mobile. I'll think about adding other numbers in a way that indicates you can or can't switch with shortcuts.

**Comment by misterhsp** [comment]
What you should also change is that you can select the text with the mouse.

...

**Comment by MartinBriza** [comment]
Closed with dd30cf5789fb3bfffc719b05e15a836c1c4fe264

**Comment by misterhsp** [comment]
I always see only 1 to 10. The rest has no numbers

**Comment by MartinBriza** [comment]
It's changed in versions 1.3.17 and later. If you're on iOS, it will get updated by Monday.

**Comment by misterhsp** [comment]
I have installed 1.3.24

apt policy lith
lith:
   Installiert:           1.3.24-1
   Installationskandidat: 1.3.24-1
   Versionstabelle:
  *** 1.3.24-1 500
         500 https://hsp2/sidpkgs sid/main amd64 Packages
         100 /var/lib/dpkg/status





Am 27.11.22 um 12:42 schrieb Martin Bříza:

**Comment by MartinBriza** [comment]
![image](https://user-images.githubusercontent.com/3977440/204136881-2617fd60-cd7a-4e57-a623-887dc63c9d49.png)
It's definitely there, see the screenshot above.

**Comment by misterhsp** [comment]
I have here only from 1 to 10. Nothing more



Am 27.11.22 um 14:08 schrieb Martin Bříza:

**Comment by MartinBriza** [comment]
Well, have you actually built the right tag? Are you actually running the right binary? The color themes are hardcoded into the application, it should look the same regardless of the environment you're using, so I'm really strongly convinced it should be fine on your end as well.

**Comment by misterhsp** [comment]
I can't say anything else, 1- 10.
And yes, I built the right tag

But anyway, it's not that important now.



Am 27.11.22 um 14:18 schrieb Martin Bříza:
