### ISSUE TITLE
iOS: reconnect on resume

### ISSUE THREAD

**Issue by dennmtr** [LithApp/Lith#126]
App doesn't reconnect when returns from background to foreground after some hour(s). It says socket error connecting

**Comment by chinese-soup** [comment]
I believe this has been fixed now, haven't ran into this in a while, Lith always reconnects when resuming it after it's been killed by iOS already.

**Comment by MartinBriza** [comment]
Yeah I think it's been reconnecting pretty reliably now. Get in touch if you still have issues though!
