### ISSUE TITLE
Can't disable 'align nick length' after setting up something else

### ISSUE THREAD

**Issue by stacyharper** [LithApp/Lith#130]
The value get back to '0' while saving.

**Comment by yeled** [comment]
damn, I hit this last night too!

**Comment by chinese-soup** [comment]
Works for me on iOS just fine. 🤔 

https://github.com/LithApp/Lith/assets/5108747/22403fcf-8cbf-4c6c-9bfb-be89ad3b2a1a

**Comment by MartinBriza** [comment]
Yes, I tried to reproduce it by setting a few other options but I didn't manage to break it as well. Please let me know what sequence of actions triggers the bug if it happens again.

**Comment by stacyharper** [comment]
I am using Lith from Linux. I don't know about iOS.

**Comment by MartinBriza** [comment]
this will be the same on all platforms but i need the steps to reproduce
the bug

**Comment by stacyharper** [comment]
Fine, here a video demonstrating the bug:

https://github.com/LithApp/Lith/assets/14213590/7bc7b60b-915f-421b-9d4f-71616a61809b

**Comment by stacyharper** [comment]
Also, this come from an Alpine Linux edge, running Lith 1.3.34.

**Comment by yeled** [comment]
I'm not sure what triggered it. But if I "Save" `Disabled` then it immediately goes to `0`

**Comment by syyyr** [comment]
Does this fix the issue for you? https://github.com/LithApp/Lith/pull/131

**Comment by stacyharper** [comment]
I confirm this works. Thanks!

**Comment by yeled** [comment]
fixed!
