### ISSUE TITLE
iOS: Setting light theme in Lith without system-wide light theme makes the status bar unreadable

### ISSUE THREAD

**Issue by chinese-soup** [LithApp/Lith#146]
![image](https://github.com/LithApp/Lith/assets/5108747/7a71f061-b434-4287-b00a-1adcc7fea171)

Reproduce:
1) force set lith to light theme
2) set phone (ios) to dark theme
3) clock and carrier etc. is white text on white bg

**Comment by MartinBriza** [comment]
You know what, I just won't do this. My phone renders the clock just fine without any explicit handling so I guess it's fine on newer versions of iOS and spending time on this is not worth it.
