### ISSUE TITLE
Mobile: Scrollbar disappearing after a long time

### ISSUE THREAD

**Issue by chinese-soup** [LithApp/Lith#20]
When you scroll up and down a buffer the scrollbar appears, when you stop scrolling the scrollbar disappears after more than 2 seconds. This can be annoying when you want to press the "open picture" button while the scrollbar is visible as it is overlayed on top of the "open picture button" and therefore you click on the scrollbar and scroll up/down accidentally. This is more noticeable on small screens :^)

**Comment by MartinBriza** [comment]
The scrollbar is next to invisible now and image previewer is changed as well so this is a non-issue now

**Comment by chinese-soup** [comment]
based and j pilled
