### ISSUE TITLE
Link action window positioned oob

### ISSUE THREAD

**Issue by chinese-soup** [LithApp/Lith#50]
Nevim jak lip to popsat.

![E7E3ADB4-BB28-4181-955C-FC958BD89A50](https://user-images.githubusercontent.com/5108747/98697963-cbaa1800-2375-11eb-89bc-329c5bbb54cd.png)

**Comment by MartinBriza** [comment]
Closed with 90fc44ce221aeaef68ceed44caa360bf9b502a70
