### ISSUE TITLE
This URL gets parsed wrong

### ISSUE THREAD

**Issue by MartinBriza** [LithApp/Lith#56]
https://scontent-prg1-1.xx.fbcdn.net/v/t1.0-9/18198443_1902457026668611_3011544087441344214_n.jpg?_nc_cat=104&ccb=2&_nc_sid=9267fe&_nc_ohc=hfE6q-mOIhIAX9y55zI&_nc_ht=scontent-prg1-1.xx&oh=683c2c75e375ba988fb8827c245a1d4a&oe=5FD469DB

**Comment by syyyr** [comment]
Minimal reproducer `http://j.net/?&`

**Comment by chinese-soup** [comment]
cože
