### ISSUE TITLE
Support for TOTP

### ISSUE THREAD

**Issue by roniez** [LithApp/Lith#90]
To support the newer version's of weechat and its security we need support for the TOTP function.

Accroding to the documentation from weechat the relay client needs to send totp in the init section.
```

Then your relay client must support and send the TOTP value, in addition to the password, in the "init" command:

init password=secretpassword,totp=123456
```

https://blog.weechat.org/post/2019/01/14/Support-of-TOTP

**Comment by MartinBriza** [comment]
I've tentatively planned to implement this at some point. But it's always nice to have features reported as issues so they don't fall between the cracks. Thanks.
I think I'll have another Lith programming session soon-ish and I'll definitely look into this.

**Comment by MartinBriza** [comment]
So I read some docs about this today and I think TOTP is superseded by the handshake command and it would be pretty annoying to use especially on mobile. However i f you (or anybody else) still have interest in this, reopen this ticket and I'll add it at some point.
