### ISSUE TITLE
Lith will silently not launch

### ISSUE THREAD

**Issue by atomicwrites** [LithApp/Lith#91]
I downloaded the Lith Windows release and extracted it, after launching it the first time successfully I closed it and now it will no longer open. Launching the program results in nothing other than `Lith.exe` showing up in task manager for a few seconds. It does not print anything if I launch it from a terminal. I wish I had more information to give but I can't get any message out of it.

**Comment by MartinBriza** [comment]
Ha, this seems to have been fixed already by @syyyr . I just pushed a new tag: https://github.com/LithApp/Lith/releases/tag/1.2.4 that will contain a fix. Please try it (when it builds, it should be done in a few minutes) and close the issue if it works for you. If not, I'll need the info as stated above. Thanks!

**Comment by atomicwrites** [comment]
Awesome, it works now. I was able to launch and close multiple times and also set up the relay connection.

**Comment by MartinBriza** [comment]
Yes, exactly. Thank you for trying the new release and checking back! Please keep the feedback coming :)

**Comment by atomicwrites** [comment]
One question, it looks like tab completion is not supported yet?

**Comment by MartinBriza** [comment]
Tab completion is in place but it's our custom simple solution, Lith doesn't support the completion protocol as provided by WeeChat, yet.

**Comment by MartinBriza** [comment]
The autocomplete button is hidden by default, you can enable it in the interface options. Also, the default shortcut for autocomplete is tab - it's possible to override that but only by manually editing the config file - the key is `shortcutAutocomplete`, there you can input the shortcut as a string description with `+` to combine the keys, so for example:
```
shortcutAutocomplete=Alt+f
```

**Comment by atomicwrites** [comment]
Oh OK. I tried to have it complete `/jo` to `/join` or `/con` to `/connect` but nothing happens. Are these supposed to work?

**Comment by MartinBriza** [comment]
Yeah, sorry, that's the thing about doing it ourselves: it works only for autocompleting nicks that are in the open buffer.

**Comment by MartinBriza** [comment]
Lith doesn't cover a lot of these nonessential features of the weechat protocol. This is a big one. You'll also probably notice that the hotlist implementation doesn't work very well, too. Those are the biggest gaps we have currently. And then of course also some more advanced authentication options like TOTP (as reported in another issue).

**Comment by MartinBriza** [comment]
Also, if you need anything, we're on #lith on [https://libera.chat](libera.chat). Come visit us and chat if you need anything, IRC is a much better media for discussions like this. But if you don't want to, it's fine to ask here, too, as well.
