### ISSUE TITLE
Can't connect, perhaps due to self-signed SSL

### ISSUE THREAD

**Issue by pushcx** [LithApp/Lith#92]
When I try to connect to my weechat relay, it fails, shows a partial error message (screenshot below), and then clears the error and retries in at most 1 second. Lith repeats this as long as the app is open, and the red error message moving the menu button up and down makes it difficult to tap.

![lith](https://user-images.githubusercontent.com/6262/120728339-349cdd00-c4cc-11eb-9014-3c1763c9e5fe.jpg)

I think this is because my relay has a self-signed cert. (It doesn't run a webserver to get a Let's Encrypt or other cert).

So there's a couple issues:

 * The error message is truncated and can't be read
 * The self-signed cert is trustworthy but can't be used
 * The error message should probably be below the header so it doesn't move the UI
 * The retry time is too low; a server is unlikely to fix an issue in 1 second

Hope this helps. I look forward to trying the app.

**Comment by MartinBriza** [comment]
Thanks for the report!

I see you're on an iPhone and I'm not 100% sure it's possible to mess around with the CA chain (at least according to Apple's terms). I'll look into it though. But the issue at hand is very likely to be the fact you're using a self-signed cert. I expect it doesn't work with Glowing Bear as well, am I correct?

As far as the error message goes, I'll try to make it a little less annoying (not pop up as often) when this happens.

**Comment by MartinBriza** [comment]
You're also right the error popup should be below the header bar so it doesn't move interactive elements when it appears, that's a great point.

**Comment by pushcx** [comment]
I haven't tried glowing bear - as mentioned, the vps doesn't run nginx.

**Comment by MartinBriza** [comment]
Should be fixed after b8e6ac764eff3b947d3d7a37a1efc96507156749
